# Site settings
title: Drobnjak Dent
description: "A responsive Jekyll theme for dental clinics."
baseurl: "" # the subpath of your site, e.g. /blog
url: "stomatolog-ns.com/" # the name of your domain
logo_url: svg/min/drobnjaklogo.png

# Hero
hero:
    hero_img: hero.jpg
    hero_title: <strong>  Drobnjak dent </strong>
    hero_description: <strong> Osmeh za sve generacije </strong>

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: <strong> 021 / 30 15 5 15 </strong>
    emergency: <strong> 060 / 30 13 872 </strong>
    email: <strong> drobnjakjulija@gmail.com </strong>
    address: <strong> Petra Drapšina 32/4  Novi Sad <br> I sprat </strong>

# Opening hours
monday_wednesday: <strong> 13:00 – 20:00 </strong>
thursday_friday: <strong> 7:00 – 14:00 </strong>
saturday: <strong> 8:00 - 13:00 </strong>
sunday: <strong> Neradna </strong>

# Testimonials
testimonials:
    testimonials_img: hero2.jpg

# Map
map:
    zoom: 17
    address: PETRA DRAPŠINA ,NOVI SAD
    address_details: svg/min/drobnjaklogo.png

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2017 DrobnjakDent - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
